In [3]:
import nltk

nltk.download("punkt")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../data/news.csv")

df.head()

,Title,Description
0,Obama Lays Wreath at Arlington National Cemetery,Obama Lays Wreath at Arlington National Cemete...
1,A Look at the Health of the Chinese Economy,"Tim Haywood, investment director business-unit..."
2,Nouriel Roubini: Global Economy Not Back to 2008,"Nouriel Roubini, NYU professor and chairman at..."
3,Finland GDP Expands In Q4,Finland's economy expanded marginally in the t...
4,"Tourism, govt spending buoys Thai economy in J...",Tourism and public spending continued to boost...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216900 entries, 0 to 216899
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Title        216900 non-null  object
 1   Description  216885 non-null  object
dtypes: object(2)
memory usage: 3.3+ MB

In [6]:
df.describe()

                   Title                           Description
count             216900                                216885
unique            202515                                212875
top     Today's schedule  Read full story for latest details.
freq                  43                                    18

In [7]:
df.shape

(216900, 2)

In [8]:
df.isnull().sum()

Title           0
Description    15
dtype: int64

In [10]:
df.columns

Index(['Title', 'Description'], dtype='object')

hhhhhhhheeeeeeeeeeeeeetrrrrrrrrrreeeee

In [11]:
df = df[["Title", "Description"]]
df.head()

,Title,Description
0,Obama Lays Wreath at Arlington National Cemetery,Obama Lays Wreath at Arlington National Cemete...
1,A Look at the Health of the Chinese Economy,"Tim Haywood, investment director business-unit..."
2,Nouriel Roubini: Global Economy Not Back to 2008,"Nouriel Roubini, NYU professor and chairman at..."
3,Finland GDP Expands In Q4,Finland's economy expanded marginally in the t...
4,"Tourism, govt spending buoys Thai economy in J...",Tourism and public spending continued to boost...

In [13]:
print(df.columns)

Index(['Title', 'Description'], dtype='object')

In [14]:
df.columns = df.columns.str.strip().str.lower()

In [15]:
print(df.columns)

Index(['title', 'description'], dtype='object')

In [16]:
df = df[["title", "description"]]

In [17]:
df.columns = df.columns.str.strip().str.lower()
print(df.columns)

Index(['title', 'description'], dtype='object')

In [19]:
print(df.columns)

Index(['title', 'description'], dtype='object')

In [18]:
df = df[["title", "description"]]

🎯 Mentor Question
❓ why drop other columns?

Answer (say like this):

The project constraint says we must work only with raw text.
So we keep only title and description because they contain the semantic content needed for Transformer representation learning.

In [20]:
df = df[["title", "description"]]

df.head()

,title,description
0,Obama Lays Wreath at Arlington National Cemetery,Obama Lays Wreath at Arlington National Cemete...
1,A Look at the Health of the Chinese Economy,"Tim Haywood, investment director business-unit..."
2,Nouriel Roubini: Global Economy Not Back to 2008,"Nouriel Roubini, NYU professor and chairman at..."
3,Finland GDP Expands In Q4,Finland's economy expanded marginally in the t...
4,"Tourism, govt spending buoys Thai economy in J...",Tourism and public spending continued to boost...

🎯 Mentor Question
❓ why combine title and description?

Answer:

Title contains attention-oriented words and description contains context.
Combining both gives full semantic input for the Transformer model.

In [21]:
df["text"] = df["title"] + " " + df["description"]

df.head()

,title,description,text
0,Obama Lays Wreath at Arlington National Cemetery,Obama Lays Wreath at Arlington National Cemete...,Obama Lays Wreath at Arlington National Cemete...
1,A Look at the Health of the Chinese Economy,"Tim Haywood, investment director business-unit...",A Look at the Health of the Chinese Economy Ti...
2,Nouriel Roubini: Global Economy Not Back to 2008,"Nouriel Roubini, NYU professor and chairman at...",Nouriel Roubini: Global Economy Not Back to 20...
3,Finland GDP Expands In Q4,Finland's economy expanded marginally in the t...,Finland GDP Expands In Q4 Finland's economy ex...
4,"Tourism, govt spending buoys Thai economy in J...",Tourism and public spending continued to boost...,"Tourism, govt spending buoys Thai economy in J..."

In [22]:
import re

def clean_text(text):

    text = str(text)

    text = text.lower()

    text = re.sub(r"http\S+", "", text)

    text = re.sub(r"[^a-zA-Z ]", "", text)

    text = re.sub(r"\s+", " ", text)

    return text


df["clean_text"] = df["text"].apply(clean_text)

df.head()

,title,description,text,clean_text
0,Obama Lays Wreath at Arlington National Cemetery,Obama Lays Wreath at Arlington National Cemete...,Obama Lays Wreath at Arlington National Cemete...,obama lays wreath at arlington national cemete...
1,A Look at the Health of the Chinese Economy,"Tim Haywood, investment director business-unit...",A Look at the Health of the Chinese Economy Ti...,a look at the health of the chinese economy ti...
2,Nouriel Roubini: Global Economy Not Back to 2008,"Nouriel Roubini, NYU professor and chairman at...",Nouriel Roubini: Global Economy Not Back to 20...,nouriel roubini global economy not back to nou...
3,Finland GDP Expands In Q4,Finland's economy expanded marginally in the t...,Finland GDP Expands In Q4 Finland's economy ex...,finland gdp expands in q finlands economy expa...
4,"Tourism, govt spending buoys Thai economy in J...",Tourism and public spending continued to boost...,"Tourism, govt spending buoys Thai economy in J...",tourism govt spending buoys thai economy in ja...

In [23]:
df.to_csv("../outputs/clean_news.csv", index=False)