In [1]:
import pandas as pd
import re

df = pd.read_csv("../data/news.csv")

df.columns = df.columns.str.strip().str.lower()

df = df[["title", "description"]]

df.head()

,title,description
0,Obama Lays Wreath at Arlington National Cemetery,Obama Lays Wreath at Arlington National Cemete...
1,A Look at the Health of the Chinese Economy,"Tim Haywood, investment director business-unit..."
2,Nouriel Roubini: Global Economy Not Back to 2008,"Nouriel Roubini, NYU professor and chairman at..."
3,Finland GDP Expands In Q4,Finland's economy expanded marginally in the t...
4,"Tourism, govt spending buoys Thai economy in J...",Tourism and public spending continued to boost...

In [3]:
print(df.columns)

Index(['title', 'description'], dtype='object')

In [4]:
df.columns = df.columns.str.strip().str.lower()

In [5]:
print(df.columns)

Index(['title', 'description'], dtype='object')

In [6]:
df = df[["title", "description"]]

In [7]:
df.columns = df.columns.str.strip().str.lower()
print(df.columns)

Index(['title', 'description'], dtype='object')

In [8]:
print(df.columns)

Index(['title', 'description'], dtype='object')

In [9]:
df = df[["title", "description"]]

In [10]:
df = df[["title", "description"]]

df.head()

,title,description
0,Obama Lays Wreath at Arlington National Cemetery,Obama Lays Wreath at Arlington National Cemete...
1,A Look at the Health of the Chinese Economy,"Tim Haywood, investment director business-unit..."
2,Nouriel Roubini: Global Economy Not Back to 2008,"Nouriel Roubini, NYU professor and chairman at..."
3,Finland GDP Expands In Q4,Finland's economy expanded marginally in the t...
4,"Tourism, govt spending buoys Thai economy in J...",Tourism and public spending continued to boost...

In [11]:
df["text"] = df["title"] + " " + df["description"]

df.head()

,title,description,text
0,Obama Lays Wreath at Arlington National Cemetery,Obama Lays Wreath at Arlington National Cemete...,Obama Lays Wreath at Arlington National Cemete...
1,A Look at the Health of the Chinese Economy,"Tim Haywood, investment director business-unit...",A Look at the Health of the Chinese Economy Ti...
2,Nouriel Roubini: Global Economy Not Back to 2008,"Nouriel Roubini, NYU professor and chairman at...",Nouriel Roubini: Global Economy Not Back to 20...
3,Finland GDP Expands In Q4,Finland's economy expanded marginally in the t...,Finland GDP Expands In Q4 Finland's economy ex...
4,"Tourism, govt spending buoys Thai economy in J...",Tourism and public spending continued to boost...,"Tourism, govt spending buoys Thai economy in J..."

In [12]:
import re

def clean_text(text):

    text = str(text)

    text = text.lower()

    text = re.sub(r"http\S+", "", text)

    text = re.sub(r"[^a-zA-Z ]", "", text)

    text = re.sub(r"\s+", " ", text)

    return text


df["clean_text"] = df["text"].apply(clean_text)

df.head()

,title,description,text,clean_text
0,Obama Lays Wreath at Arlington National Cemetery,Obama Lays Wreath at Arlington National Cemete...,Obama Lays Wreath at Arlington National Cemete...,obama lays wreath at arlington national cemete...
1,A Look at the Health of the Chinese Economy,"Tim Haywood, investment director business-unit...",A Look at the Health of the Chinese Economy Ti...,a look at the health of the chinese economy ti...
2,Nouriel Roubini: Global Economy Not Back to 2008,"Nouriel Roubini, NYU professor and chairman at...",Nouriel Roubini: Global Economy Not Back to 20...,nouriel roubini global economy not back to nou...
3,Finland GDP Expands In Q4,Finland's economy expanded marginally in the t...,Finland GDP Expands In Q4 Finland's economy ex...,finland gdp expands in q finlands economy expa...
4,"Tourism, govt spending buoys Thai economy in J...",Tourism and public spending continued to boost...,"Tourism, govt spending buoys Thai economy in J...",tourism govt spending buoys thai economy in ja...

In [13]:
df.to_csv("../outputs/clean_news.csv", index=False)